"use strict";
exports.__esModule = true;
var express_1 = require("express");
var networkController_js_1 = require("../controllers/networkController.js");
var authMiddleware_js_1 = require("../middlewares/authMiddleware.js");
var schemaMiddleware_js_1 = require("../middlewares/schemaMiddleware.js");
var networkSchema_js_1 = require("../schemas/networkSchema.js");
var networkRouter = (0, express_1.Router)();
networkRouter.use(authMiddleware_js_1.ensureAuthenticatedMiddleware);
networkRouter.get("/networks", networkController_js_1.getAllNetworks);
networkRouter.get("/networks/:id", networkController_js_1.getNetwork);
networkRouter.post("/networks", (0, schemaMiddleware_js_1.validateSchemaMiddleware)(networkSchema_js_1.networkSchema), networkController_js_1.createNetwork);
networkRouter["delete"]("/networks/:id", networkController_js_1.deleteNetwork);
exports["default"] = networkRouter;
