"use strict";
exports.__esModule = true;
var express_1 = require("express");
var safeNoteController_js_1 = require("../controllers/safeNoteController.js");
var authMiddleware_js_1 = require("../middlewares/authMiddleware.js");
var schemaMiddleware_js_1 = require("../middlewares/schemaMiddleware.js");
var safeNoteSchema_js_1 = require("../schemas/safeNoteSchema.js");
var safeNoteRouter = (0, express_1.Router)();
safeNoteRouter.use(authMiddleware_js_1.ensureAuthenticatedMiddleware);
safeNoteRouter.get("/safenotes", safeNoteController_js_1.getAllSafeNotes);
safeNoteRouter.get("/safenotes/:id", safeNoteController_js_1.getSafeNote);
safeNoteRouter.post("/safenotes/", (0, schemaMiddleware_js_1.validateSchemaMiddleware)(safeNoteSchema_js_1.safeNoteSchema), safeNoteController_js_1.createSafeNote);
safeNoteRouter["delete"]("/safenotes/:id", safeNoteController_js_1.deleteSafeNote);
exports["default"] = safeNoteRouter;
